@startuml
'https://plantuml.com/sequence-diagram'
!include Style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MedicalHistoryCommandParser" as MedicalHistoryCommandParser LOGIC_COLOR
participant ":MedicalHistoryCommand" as MedicalHistoryCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR_T4
end box

[-> LogicManager : execute("medical 1 m/ADHD")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("medical 1 m/ADHD")
activate AddressBookParser

create MedicalHistoryCommandParser
AddressBookParser -> MedicalHistoryCommandParser
activate MedicalHistoryCommandParser

MedicalHistoryCommandParser --> AddressBookParser
deactivate MedicalHistoryCommandParser

AddressBookParser -> MedicalHistoryCommandParser : parse(args)
activate MedicalHistoryCommandParser

create MedicalHistoryCommand
MedicalHistoryCommandParser -> MedicalHistoryCommand
activate MedicalHistoryCommand
MedicalHistoryCommand --> MedicalHistoryCommandParser
deactivate MedicalHistoryCommand

MedicalHistoryCommandParser --> AddressBookParser
deactivate MedicalHistoryCommandParser
destroy MedicalHistoryCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> MedicalHistoryCommand : execute()
activate MedicalHistoryCommand

MedicalHistoryCommand -> Model : setStudent()
activate Model

Model --> MedicalHistoryCommand

create CommandResult
MedicalHistoryCommand -> CommandResult
activate CommandResult

CommandResult --> MedicalHistoryCommand
deactivate

MedicalHistoryCommand --> LogicManager : result
deactivate MedicalHistoryCommand
destroy MedicalHistoryCommand

[<--LogicManager
deactivate LogicManager

@enduml
