@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ClearStudentCommandParser" as ClearStudentCommandParser LOGIC_COLOR
participant "c:ClearStudentCommand" as ClearStudentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteStudent 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("clearStudent ")
activate AddressBookParser

create ClearStudentCommandParser
AddressBookParser -> ClearStudentCommandParser
activate ClearStudentCommandParser

ClearStudentCommandParser --> AddressBookParser
deactivate ClearStudentCommandParser

AddressBookParser -> ClearStudentCommandParser : parse()
activate ClearStudentCommandParser

create ClearStudentCommand
ClearStudentCommandParser -> ClearStudentCommand
activate ClearStudentCommand

ClearStudentCommand --> ClearStudentCommandParser : c
deactivate ClearStudentCommand

ClearStudentCommandParser --> AddressBookParser : c
deactivate ClearStudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ClearStudentCommandParser -[hidden]-> AddressBookParser
destroy ClearStudentCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> ClearStudentCommand : execute()
activate ClearStudentCommand

ClearStudentCommand -> Model : clearStudent()
activate Model

Model --> ClearStudentCommand
deactivate Model

create CommandResult
ClearStudentCommand -> CommandResult
activate CommandResult

CommandResult --> ClearStudentCommand
deactivate CommandResult

ClearStudentCommand --> LogicManager : result
deactivate ClearStudentCommand

[<--LogicManager
deactivate LogicManager
@enduml

