@startuml
'https://plantuml.com/sequence-diagram'

[-> LogicManager : execute("filterStudent class")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("filterStudent class")
activate AddressBookParser

create FilterStudentCommandParser
AddressBookParser -> FilterStudentCommandParser
activate FilterStudentCommandParser

FilterStudentCommandParser --> AddressBookParser
deactivate FilterStudentCommandParser

AddressBookParser -> FilterStudentCommandParser : parse(arguments)
activate FilterStudentCommandParser

create StudentInvolvementContainsKeywordsPredicate
FilterStudentCommandParser ->  StudentInvolvementContainsKeywordsPredicate
activate StudentInvolvementContainsKeywordsPredicate

create FilterStudentCommand
StudentInvolvementContainsKeywordsPredicate -> FilterStudentCommand
activate FilterStudentCommand

FilterStudentCommand --> StudentInvolvementContainsKeywordsPredicate
deactivate FilterStudentCommand

StudentInvolvementContainsKeywordsPredicate --> FilterStudentCommandParser
deactivate

FilterStudentCommandParser --> AddressBookParser
deactivate FilterStudentCommandParser
FilterStudentCommandParser -[hidden]-> AddressBookParser
destroy FilterStudentCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> FilterStudentCommand : execute()
activate FilterStudentCommand

FilterStudentCommand -> Model : updateFilteredStudentList(predicate)
activate Model

Model --> FilterStudentCommand
deactivate Model

FilterStudentCommand -> Model : getFilteredStudentList()
activate Model

Model --> FilterStudentCommand
deactivate Model



create CommandResult
FilterStudentCommand -> CommandResult
activate CommandResult

CommandResult --> FilterStudentCommand
deactivate CommandResult

FilterStudentCommand --> LogicManager : result
deactivate FilterStudentCommand
FilterStudentCommand -[hidden]-> LogicManager
destroy FilterStudentCommand

[<--LogicManager
deactivate LogicManager
@enduml