@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
show members
hide empty members

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
'make it private?
Class ModelManager {
    history : Stack<AddressBook>
}
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueStudentList
Class UniqueTeacherList
Class UniqueTeacherList
Class NonConflictMeetingList
Class Student
Class Teacher
Class Meeting
Class "{abstract}\nPerson" as Person
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueStudentList
AddressBook *--> "1" UniqueTeacherList
AddressBook *--> "1" NonConflictMeetingList
UniqueStudentList --> "~* all" Student
UniqueTeacherList --> "~* all" Teacher
NonConflictMeetingList --> "~* all" Meeting

ModelManager -->"~* filtered" Student
ModelManager -->"~* filtered" Teacher

Teacher --|> Person
Student --|> Person

@enduml
